version: '3.9'

services:
  backend:
    container_name: backend_dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app                  # Mount code for live changes
    env_file:
      - .env.dev                          # Environment variables
    ports:
      - "8000:8000"                             # Expose backend
    depends_on:
      - postgres                                # Wait for database

  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app                         # Mount app code for live changes
      - /app/node_modules/                      # Skip binding node_modules
    ports:
      - "5173:5173"                             # Expose React dev server
    stdin_open: true                            # Keeps dev server logs visible

  nginx:
    container_name: nginx_dev
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
#      - ./nginx/nginx_dev.conf:/etc/nginx/nginx.conf  # Mount nginx config for live changes
      - ./nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf  # Mount into conf.d for proper hierarchy

    ports:
      - "80:80"                                 # Expose Nginx
    depends_on:
      - backend
      - frontend

  postgres:
    container_name: postgres_dev
    image: postgres:15
    volumes:
      - database:/var/lib/postgresql/data         # Persist database data
    env_file:
      - .env.dev
    ports:
      - "5432:5432"                             # Expose database

volumes:
  database: